<?php

namespace DoctrineProxies\__CG__\predaddy\domain\impl\doctrine;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \predaddy\domain\impl\doctrine\Event implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'sequenceNumber', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'stateHash', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'aggregateId', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'aggregateType', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'eventType', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'data', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'created');
        }

        return array('__isInitialized__', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'sequenceNumber', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'stateHash', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'aggregateId', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'aggregateType', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'eventType', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'data', '' . "\0" . 'predaddy\\domain\\impl\\doctrine\\Event' . "\0" . 'created');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Event $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAggregateId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAggregateId', array());

        return parent::getAggregateId();
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array());

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toString', array());

        return parent::toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getSequenceNumber()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSequenceNumber();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSequenceNumber', array());

        return parent::getSequenceNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getAggregateType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAggregateType', array());

        return parent::getAggregateType();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventType', array());

        return parent::getEventType();
    }

    /**
     * {@inheritDoc}
     */
    public function stateHash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'stateHash', array());

        return parent::stateHash();
    }

    /**
     * {@inheritDoc}
     */
    public function hashCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hashCode', array());

        return parent::hashCode();
    }

    /**
     * {@inheritDoc}
     */
    public function equals(\precore\lang\ObjectInterface $object = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'equals', array($object));

        return parent::equals($object);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
